import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import {
  FileText,
  Bot,
  ShieldCheck,
  UploadCloud,
  BarChart,
  Bell,
  Heart,
} from 'lucide-react';
import Logo from '@/components/logo';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { PlaceHolderImages } from '@/lib/placeholder-images';

export default function Home() {
  const testimonial1Avatar = PlaceHolderImages.find(
    (img) => img.id === 'testimonial-1-avatar'
  );
  const testimonial2Avatar = PlaceHolderImages.find(
    (img) => img.id === 'testimonial-2-avatar'
  );

  return (
    <div className="flex flex-col min-h-screen">
      <header className="container mx-auto px-4 py-6">
        <Logo />
      </header>
      <main className="flex-1">
        <section className="container mx-auto px-4 py-16 text-center">
          <h1 className="text-4xl md:text-6xl font-bold font-headline tracking-tight mb-4">
            Your Health Story, Reimagined.
          </h1>
          <p className="text-lg md:text-xl text-muted-foreground max-w-3xl mx-auto mb-8">
            LifeFile provides a secure, unified view of your medical history,
            empowered by AI to deliver personalized insights and proactive health
            alerts.
          </p>
          <Button asChild size="lg">
            <Link href="/login">Access Your Dashboard</Link>
          </Button>
        </section>

        <section className="bg-muted py-20">
          <div className="container mx-auto px-4">
            <h2 className="text-3xl font-bold text-center mb-12 font-headline">
              Features
            </h2>
            <div className="grid md:grid-cols-3 gap-8">
              <Card>
                <CardHeader className="items-center">
                  <FileText className="w-10 h-10 mb-4 text-primary" />
                  <CardTitle>Comprehensive History</CardTitle>
                </CardHeader>
                <CardContent className="text-center">
                  <p className="text-muted-foreground">
                    View your complete medical journey—from check-ups to
                    prescriptions—all in one place.
                  </p>
                </CardContent>
              </Card>
              <Card>
                <CardHeader className="items-center">
                  <Bot className="w-10 h-10 mb-4 text-primary" />
                  <CardTitle>AI-Powered Insights</CardTitle>
                </CardHeader>
                <CardContent className="text-center">
                  <p className="text-muted-foreground">
                    Get easy-to-understand summaries, health risk alerts, and
                    preventive tips generated by AI.
                  </p>
                </CardContent>
              </Card>
              <Card>
                <CardHeader className="items-center">
                  <ShieldCheck className="w-10 h-10 mb-4 text-primary" />
                  <CardTitle>Secure & Private</CardTitle>
                </CardHeader>
                <CardContent className="text-center">
                  <p className="text-muted-foreground">
                    Your data is protected with role-based access, ensuring
                    confidentiality and control.
                  </p>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>

        <section className="py-20">
          <div className="container mx-auto px-4">
            <h2 className="text-3xl font-bold text-center mb-12 font-headline">
              How It Works
            </h2>
            <div className="grid md:grid-cols-3 gap-8 text-center">
              <div className="flex flex-col items-center">
                <div className="p-4 bg-primary/10 rounded-full mb-4">
                  <UploadCloud className="w-10 h-10 text-primary" />
                </div>
                <h3 className="text-xl font-semibold mb-2">
                  1. Add Your Records
                </h3>
                <p className="text-muted-foreground">
                  Securely upload or link your medical documents from various
                  providers.
                </p>
              </div>
              <div className="flex flex-col items-center">
                <div className="p-4 bg-primary/10 rounded-full mb-4">
                  <BarChart className="w-10 h-10 text-primary" />
                </div>
                <h3 className="text-xl font-semibold mb-2">
                  2. Get AI Insights
                </h3>
                <p className="text-muted-foreground">
                  Our AI analyzes your history to generate summaries and identify
                  potential health risks.
                </p>
              </div>
              <div className="flex flex-col items-center">
                <div className="p-4 bg-primary/10 rounded-full mb-4">
                  <Bell className="w-10 h-10 text-primary" />
                </div>
                <h3 className="text-xl font-semibold mb-2">
                  3. Stay Proactive
                </h3>
                <p className="text-muted-foreground">
                  Receive personalized tips and alerts to better manage your health
                  journey.
                </p>
              </div>
            </div>
          </div>
        </section>

        <section className="bg-muted py-20">
          <div className="container mx-auto px-4">
            <h2 className="text-3xl font-bold text-center mb-12 font-headline">
              What Our Users Say
            </h2>
            <div className="grid md:grid-cols-2 gap-8 max-w-4xl mx-auto">
              <Card>
                <CardContent className="pt-6">
                  <div className="flex items-center gap-4">
                    {testimonial1Avatar && (
                      <Avatar>
                        <AvatarImage
                          src={testimonial1Avatar.imageUrl}
                          alt="John S."
                          data-ai-hint={testimonial1Avatar.imageHint}
                        />
                        <AvatarFallback>JS</AvatarFallback>
                      </Avatar>
                    )}
                    <div>
                      <p className="font-semibold">John S.</p>
                      <p className="text-sm text-muted-foreground">
                        Verified User
                      </p>
                    </div>
                  </div>
                  <blockquote className="mt-4 italic text-muted-foreground">
                    "LifeFile has been a game-changer. For the first time, I
                    have all my medical information in one place, and the AI
                    summary helped me understand my health better."
                  </blockquote>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="pt-6">
                  <div className="flex items-center gap-4">
                    {testimonial2Avatar && (
                      <Avatar>
                        <AvatarImage
                          src={testimonial2Avatar.imageUrl}
                          alt="Maria P."
                          data-ai-hint={testimonial2Avatar.imageHint}
                        />
                        <AvatarFallback>MP</AvatarFallback>
                      </Avatar>
                    )}
                    <div>
                      <p className="font-semibold">Maria P.</p>
                      <p className="text-sm text-muted-foreground">
                        Verified User
                      </p>
                    </div>
                  </div>
                  <blockquote className="mt-4 italic text-muted-foreground">
                    "I love the preventive tips feature. It feels like having a
                    personal health assistant guiding me towards a healthier
                    lifestyle."
                  </blockquote>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
      </main>
      <footer className="container mx-auto px-4 py-12 text-center">
        <div className="bg-primary text-primary-foreground p-8 rounded-lg">
          <h2 className="text-2xl font-bold mb-2 font-headline">
            Take Control of Your Health Today
          </h2>
          <p className="mb-4">
            Join LifeFile and start building a smarter, clearer picture of your health story.
          </p>
          <Button asChild size="lg" variant="secondary">
            <Link href="/login">Get Started</Link>
          </Button>
        </div>
        <p className="mt-8 text-muted-foreground">
          &copy; {new Date().getFullYear()} LifeFile. All rights reserved.
        </p>
      </footer>
    </div>
  );
}
